name: "Metablock Web"
description: "Deploy a new version of an html block to metablock cloud"
inputs:
  token:
    description: "Metablock API token - can be set via the METABLOCK_API_TOKEN env variable"
  block:
    description: "Metablock Block ID - can be set via the METABLOCK_BLOCK_ID env variable"
  org:
    description: "Metablock organization id - can be set via the METABLOCK_ORG_ID env variable"
  bundle:
    description: "Filesystem location of the bundle to deploy"
    default: "./dist"
  env:
    description: "Metablock environment - can be set via the METABLOCK_ENV env variable"
    default: "stage"
  name:
    description: "Optional deployment name - can be set via the METABLOCK_NAME env variable"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - metablock
    - ship
    - ${{ inputs.bundle }}
    - "--token"
    - ${{ inputs.token }}
    - "--block-id"
    - ${{ inputs.block }}
    - "--org"
    - ${{ inputs.org }}
    - "--env"
    - ${{ inputs.env }}
    - "--name"
    - ${{ inputs.name }}
